# Generated by Django 3.1.4 on 2020-12-16 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20201216_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.OneToOneField(db_column='post', on_delete=django.db.models.deletion.DO_NOTHING, to='news.post'),
        ),
    ]
