# Generated by Django 3.1.4 on 2020-12-18 15:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0014_auto_20201218_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentator',
            field=models.ForeignKey(db_column='commentator', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(db_column='post', on_delete=django.db.models.deletion.DO_NOTHING, to='news.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(db_column='author', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 15, 44, 20, 410198, tzinfo=utc)),
        ),
    ]
