# Generated by Django 3.1.4 on 2020-12-18 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20201218_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 15, 44, 53, 748513, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 15, 44, 53, 748513, tzinfo=utc)),
        ),
    ]
